### PR TITLE
US01-03-navbar

### PR DESCRIPTION
**Pull request by ChrisColesnicov**
First issue of navbar component, with only icons placeholders and animated separation bar.
HTML & CSS done, icon functions & burger menu to be issued in further update.

### CODE REVIEW

**Comment by ChrisColesnicov** [comment]
The issue highlighted in linters is about a svg file named logong.svg...but for some reason, github sees it as logoNG.svg. I'm absolutely positive that i have this marked as logong.svg in my system, in the files, in the code, and in my finder.
So the fix here is quick, but i'd like an opinion from Kevin or Cyrielle on this issue. (of course I checked what i pushed many times)

**Review by kpeset — APPROVED** [review]
Super :) Bon boulot !

**Review by kpeset — APPROVED** [review]
C'est mieux :)

**Review by geoffpech — APPROVED** [review]
bravo notre chris !!!

**Pull request merged**
